language: python
os: linux
dist: bionic
sudo: true
python:
- "3.6"
- "3.7"
- "3.8"
- "3.9-dev"
- "nightly"
# command to install dependencies
install:
- python setup.py -q install
- pip install coverage
- pip install coveralls
# command to run tests
script:
- coverage run --source=syncset -m unittest
after_success:
    coveralls
